site_name: Discord hCaptcha Document
theme:
  name: "material"
  language: "ja"
extra:
  search:
    language: "ja"
extra_css:
  - css/custom.css
nav:
  - ホーム: index.md
  - コマンド: command.md
  - 注意: attention.md
