site_name: Discord hCaptcha Document
site_url: https://discord-hcaptcha.doc.v-sli.me/
site_description: Discord hCaptchaの公式ドキュメント
site_author: Hidemaru
copyright: Hidemaru
markdown_extensions:
  - admonition
theme:
  name: "material"
  language: "ja"
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Hidemaru_OwO
    - icon: fontawesome/brands/github
      link: https://github.com/HidemaruOwO
  search:
    language: "ja"
extra_css:
  - css/custom.css
nav:
  - ホーム: index.md
  - コマンド: command.md
  - 注意: attention.md
